{* $Id: manifest_pdf_detail.tpl 12544 2011-05-27 10:34:19Z bimib $ *}
<!--<pre>
{$order_info|print_r}</pre> -->
{literal}
<style type="text/css">
.sortable th{ padding: 0px 5px; font: 10px Verdana, Geneva, sans-serif;}
.sortable td, .sortable tr:hover td{ border-right: 1px solid #e4e4e4; font: 8px Verdana, Geneva, sans-serif;}
</style>
{/literal}
<h1 style="padding: 0 0 10px 0; font:Verdana, Geneva, sans-serif; color:#0A9CCC;">Manifest Report</h1>
<div style="float:left; padding: 0 20px 0 0; font: 12px Verdana, Geneva, sans-serif;">
	<span><strong>Manifest ID:</strong> {$manifest_id}</span><br />
	<span><strong>Carrier Name:</strong> {$courier_name|replace:'_':' '}</span><br />
    <span><strong>Dispatch Date:</strong> {$dispatch_date}</span><br />
    <span><strong>No. Of Shipments:</strong> {$order_info|count}</span><br /><br />
</div>
<div style="float:left; font: 12px Verdana, Geneva, sans-serif;">
     <span><strong>Pick Up Boy:</strong> {$boy_name}</span><br />
    <span><strong>Pick Up Vehicle No:</strong> {$vehicle_no}</span><br />
    <span><strong>Pick Up By Location:</strong> {$by_location}</span><br />
    <span><strong>Report Generated By:</strong> {$report_by}</span><br />
    <span><strong>Manifest Type:</strong> {$manifest_type_name}</span><br />
    <span><strong>Notes:</strong> {$notes}</span><br /><br />
</div>
<div style="clear:both;"></div>
<table border="0" cellpadding="5" cellspacing="0" width="100%" class="table sortable" style="border-left: 1px solid #e4e4e4;border-top: 1px solid #e4e4e4;">
<tr>
	<th align="center" width="5%" style="font:bold 12px Verdana, Geneva, sans-serif; border-right: 1px solid #e4e4e4;border-bottom: 1px solid #e4e4e4;">SL No.</th>
	<th align="center" width="5%" style="font:bold 12px Verdana, Geneva, sans-serif; border-right: 1px solid #e4e4e4;border-bottom: 1px solid #e4e4e4;">Order No.</th>
    <th align="center" width="25%" style="font:bold 12px Verdana, Geneva, sans-serif;border-right: 1px solid #e4e4e4;border-bottom: 1px solid #e4e4e4;">Buyer Deatils</th>
    <th align="center" width="10%" style="font:bold 12px Verdana, Geneva, sans-serif;border-right: 1px solid #e4e4e4;border-bottom: 1px solid #e4e4e4;">Product Name</th>
    <th align="center" width="10%" style="font:bold 12px Verdana, Geneva, sans-serif;border-right: 1px solid #e4e4e4;border-bottom: 1px solid #e4e4e4;">Order Total</th>
    <th align="center" width="15%" style="font:bold 12px Verdana, Geneva, sans-serif;border-right: 1px solid #e4e4e4;border-bottom: 1px solid #e4e4e4;">Payment Mode</th>
    <th align="center" width="15%" style="font:bold 12px Verdana, Geneva, sans-serif;border-right: 1px solid #e4e4e4;border-bottom: 1px solid #e4e4e4;">Shipment Weight</th>
    <th align="center" width="15%" style="font:bold 12px Verdana, Geneva, sans-serif;border-right: 1px solid #e4e4e4;border-bottom: 1px solid #e4e4e4;">Tracking No.</th>
</tr>
{if $order_info}
{assign var="sl" value='1'}
{foreach from=$order_info item="order_details" key="k"}
    {assign var="oid" value=$order_details.order_id}

{hook name="manifest_create:manifest_now"}
<tr {cycle values="class=\"table-row\", "}>
	<td align="center" style="font: 10px Verdana, Geneva, sans-serif;border-right: 1px solid #e4e4e4;border-bottom: 1px solid #e4e4e4;">{$sl++}</td>
	<td align="center" style="font: 10px Verdana, Geneva, sans-serif;border-right: 1px solid #e4e4e4;border-bottom: 1px solid #e4e4e4;">
		{$order_details.order_id}
	</td>
    <td align="left" style="font: 10px Verdana, Geneva, sans-serif;border-right: 1px solid #e4e4e4;border-bottom: 1px solid #e4e4e4;">
		{$order_details.b_firstname} {$order_details.b_lastname}<br />{$order_details.s_address} {$order_details.s_address_2} {$order_details.s_city} {$order_details.s_state_descr} {$order_details.s_zipcode} {$order_details.b_phone} 
	</td>
    <td align="left" style="font: 10px Verdana, Geneva, sans-serif;border-right: 1px solid #e4e4e4;border-bottom: 1px solid #e4e4e4;">
		{$prod_details.$k.$oid.prod_detail}
    </td>
    <td align="center" style="font: 10px Verdana, Geneva, sans-serif;border-right: 1px solid #e4e4e4;border-bottom: 1px solid #e4e4e4;">
		{$order_details.subtotal|number_format:2:".":","}
    </td>
    <td align="left" style="font: 10px Verdana, Geneva, sans-serif;border-right: 1px solid #e4e4e4;border-bottom: 1px solid #e4e4e4;">
		{if $order_details.payment_method.payment == '' && !isset($order_details.use_gift_certificates)}
        	CluesBucks
        {elseif isset($order_details.use_gift_certificates)}
        	Gift Certificate
        {else}
        	{$order_details.payment_method.payment}
        {/if}
    </td>
    <td align="center" style="font: 10px Verdana, Geneva, sans-serif;border-right: 1px solid #e4e4e4;border-bottom: 1px solid #e4e4e4;">
		{$order_info.$k.$oid.weight}
    </td>
    <td align="center" style="font: 10px Verdana, Geneva, sans-serif;border-right: 1px solid #e4e4e4;border-bottom: 1px solid #e4e4e4;">
		{$order_info.$k.$oid.track_no}
    </td>
</tr>
{/hook}
{/foreach}
{else}
<tr>
	<td colspan="20">Data Not Found</td>
</tr>
{/if}
</table>
