<?php
$config['query_execlude_memcache'] = array("from cscart_promotions",
                                        "cscart_orders",
					"cscart_order_data",
					"reward_point",
					"SELECT profile_id, profile_type, profile_name,s_title,s_firstname,s_lastname,s_address, s_address_2, s_city,  s_state ,s_country ,s_zipcode ,s_phone FROM",
					"cscart_order_details",
                                        "catedfsdfgory_sfdid",
                                        "clues_popasdfasdular_bransadfsdds",
                                        "clues_photo_contest",
                                        "clues_fb_comment",
                                        "clues_fb_users",
                                        "gift_certificates",
                                        "select * from clues_express_checkout_setup where user_id=",
                                        "user_data",
                                        "select * from clues_deals",
"SELECT image_id,user_id,image_name,fb_like,fb_share FROM clues_scrapbook_images Where status='A' order by image_id DESC",
"SELECT  id, category_id, category, icon_path, images_path FROM clues_scrapbook_categories WHERE status='A'",
                                        "select * from clues_deals where group_id=",
                                        "select * from clues_mobile_deals",
                                        "SELECT * FROM cscart_user_session_products WHERE user_id =",
                                        "select * from clues_photo_contest where type=1",
					"select * from clues_photo_contest where type=1 order by like_click desc",
					'SELECT COUNT( * ) as count FROM  `cscart_user_session_products` WHERE type = \'C\' and user_id =',
					"clues_fb_quiz",
                                        "cscart_users",
                                        "SELECT profile_id, profile_type, profile_name,s_title,s_firstname,s_lastname,s_address, s_address_2, s_city, s_state ,s_country ,s_zipcode ,s_phone ,verified FROM cscart_user_profiles WHERE user_id =",
                                        "clues_fb_winner",
                                        "SELECT cu.email, cu.user_id, cud.type, cud.data FROM cscart_users cu LEFT JOIN cscart_user_data cud ON",
                                        "cscart_reward_point_changes",
                                        "select number_of_use from clues_limited_promotion_use where coupon_code=",
					"select user_id,email,status from cscart_orders where order_id=",
                                        "SELECT * FROM cscart_user_profiles WHERE user_id =",
                                        "select cod.order_id from cscart_order_details cod left join clues_user_product_rating cupr on cupr.order_id=cod.order_id and cupr.product_id=cod.product_id where cod.order_id",
                                        "cscart_orders.payment_id from cscart_order_details left join clues_user_product_rating on",
                                        "SELECT cscart_products.tracking, cscart_products.amount, cscart_products.min_qty, cscart_products.max_qty, cscart_products.qty_step, cscart_products.list_qty_count, cscart_product_descriptions.product FROM cscart_products LEFT JOIN cscart_product_descriptions ON cscart_product_descriptions.product_id",
                                        "SELECT amount FROM cscart_product_options_inventory WHERE combination_hash =",
					"SELECT amount, product_code FROM cscart_products WHERE product_id =",
					"select count as count from cscart_promotion_descriptions where promotion_id='' and (internal_name like '%omg%')",
"select count as count from cscart_promotion_descriptions where promotion_id='' and (internal_name like '%trootrac%')",
"select count as count from cscart_promotion_descriptions where promotion_id='' and internal_name like '' ",
"select count as count from cscart_products_categories where product_id='' and category_id=''",
					"SELECT amount, product_code FROM cscart_product_options_inventory WHERE combination_hash",
					"SELECT product_code FROM cscart_products WHERE product_id =",
					"select amount from cscart_products where product_id =",
                                        "SELECT email FROM cscart_companies WHERE company_id",
                                        "SELECT * FROM cscart_users WHERE email =",
                                        "SELECT b_firstname, b_lastname, b_address, b_zipcode FROM cscart_user_profiles WHERE user_id",
                                        "SELECT password FROM cscart_users WHERE user_id = ",
"SELECT csc1.message as question,csc.message as answer,csc.timestamp FROM clues_seller_connect as csc INNER JOIN clues_seller_connect as csc1",
                                        "select mfs.company_id,mfs.timestamp,c.company,c.status from clues_my_favourite_store");
$config['checkout_slave_query'] = array("cscart_blocks",
                                        "cscart_block_positions",
                                        "cscart_languages",
                                        "cscart_images_links",
                                        "cscart_block_location_descriptions",
                                        "cscart_language_values",
                                        "cscart_seo_names",
                                        "cscart_settings",
                                        "cscart_localizations",
                                        "cscart_currencies",
                                        "cscart_block_location_properties",
                                        "cscart_static_data",
                                        "cscart_payments",
                                        "cscart_addon_descriptions",
                                        "cscart_common_descriptions",
                                        "cscart_pages",
                                        "cscart_block_descriptions",
                                        "clues_popular_brands",
                                        "cscart_profile_field_descriptions",
                                        "cscart_state_descriptions",
                                        "cscart_country_descriptions",
                                        "fulfillment_id",
                                        "clues_carriers_service_area",
                                        "cscart_states",
                                        "cscart_destination_elements",
                                        "cscart_shipping_rates",
                                        "check_mdf_serviceability",
					"clues_advance_awb_preference",
					"SELECT * FROM clues_payment_types",
					"cscart_addons",
					"cscart_reward_points",
					"SELECT a.shipping_id, a.rate_calculation, a.service_id, a.params",
					"SELECT tax_ids FROM cscart_shippings",
					"SELECT product FROM cscart_product_descriptions WHERE product_id =",
					"SELECT category_id, parent_id FROM cscart_categories WHERE parent_id",
					"SELECT id_path FROM cscart_categories",
					"select failed_status from clues_payment_option_pgw where",
					"SELECT * from clues_mass_coupon_code where coupon_code",
					"cscart_countries",
					"SELECT category_id FROM cscart_products_categories WHERE product_id",
					"SELECT REPLACE(id_path");

?>
