{* $Id: export_order_list.tpl 12544 2011-05-27 10:34:19Z bimib $ *}
{script src="lib/amcharts/swfobject.js"}
{literal}
<style type="text/css">
.left_box{ float:left; padding: 0 20px 0 0;}
.right_box{ float:left;}
</style>
{/literal}
<h1 class="mainbox-title">Manifest Creation System</h1>
<p><strong>Step1: Enter Order Numbers</strong> | Step2: Review  Manifest | Step3: Create Manifest Report</p>
 
<form method="post" action="{""|fn_url}" name="manifest_generate_form" id="manifest_generate_form" enctype="multipart/form-data">
<div class="left_box">
    <div class="form-field">
    <label for="by_location" class="cm-required">Pick Up By Location:</label><!--<input type="text" name="by_location" id="by_location"  />-->
    {if $by_location}
    <select name="by_location" id="by_location">
        <option value="">-- Select --</option>
        {foreach from=$by_location item=item key=key}
        {if $item.sorting_center_display_name}
            <option value="{$item.sorting_center_display_name}">{$item.sorting_center_display_name}</option>
        {else}
            <option value="{$item.company_name},{$item.warehouse_state},{$item.warehouse_city}">{$item.company_name},{$item.warehouse_state},{$item.warehouse_city}</option>
        {/if}
        {/foreach}
    </select>
    {/if}
    {if $vendor_location}
    <input type="text" name="by_location" id="by_location" value="{$vendor_location}" readonly="readonly" />
    {/if}
    </div>
    <div class="form-field">

        <label for="carrier_key" class="cm-required">{$lang.carrier}:</label>
        <select id="carrier_key" name="shipment_data[carrier]">
            <option value="">-- Select --</option>
            <option value="FDX">{$lang.fedex}</option>
            <option value="First_Flight">{$lang.mycarrier_First_Flight}</option>
            <option value="Gati">{$lang.mycarrier_Gati}</option>
            <option value="Maruti_Courier">{$lang.mycarrier_Maruti_Courier}</option>
            <option value="blue_dart">{$lang.mycarrier_blue_dart}</option>
            <option value="DTDC">{$lang.mycarrier_dtdc}</option>
            <option value="India_Post_Registered">{$lang.mycarrier_india_post_registered}</option>
            <option value="PRofessional">{$lang.mycarrier_professional}</option>
            <option value="Quantum">{$lang.mycarrier_quantum}</option>
            <option value="Aramax">{$lang.mycarrier_aramax}</option>
            <option value="YadavEnterprises">{$lang.yadaventerprises}</option>
        </select>
    </div>
    <div class="form-field">
    <label for="dispatch_date" class="cm-required">Dispatch Date:</label>
    {include file="common_templates/calendar.tpl" date_id="dispatch_date" date_name="dispatch_date"  date_val=$smarty.now|date_format:"%d:%m:%Y" start_year=$settings.Company.company_start_year extra="onchange=\"$('#`$prefix`period_selects').val('C');\""}
    </div>
     <div class="form-field">
    <label for="manifest_type" class="cm-required">Manifest Type:</label><!--<input type="text" name="by_location" id="by_location"  />-->
    {if $manifest_type}
    <select name="manifest_type" id="manifest_type">
        <option value="">-- Select --</option>
        {foreach from=$manifest_type item=item key=key}
            <option {if $manf_drop_id == $item.manifest_type_id}selected="selected"{/if} value="{$item.manifest_type_id}">{$item.description}</option>
        {/foreach}
    </select>
    {/if}
    </div>
    <!-- <div class="form-field">
    <label>Dispatch Report Only</label>
    <input type="checkbox" name="dispatch_report" value="1" /> Please check for dispatch Report Only
    </div> -->
    <div class="form-field">
    <label for="upload_csv_file">Upload File with Order Numbers<br /> (CSV File Only):</label><input type="file" name="file" id="upload_csv_file"  />
    </div>
    <div class="form-field">
    OR
    </div>
    <div class="form-field">
    <label></label>
    Enter order numbers in the text area below. <br />Please enter one order number per line.<br /><br />
    <textarea name="text_area" id="upload_csv_file" rows="10"></textarea>
    </div>
    
</div>
<div class="right_box">
    <div class="form-field">
    <label for="boy_name">Pick Up By:</label><input type="text" name="boy_name" id="boy_name"  />
    </div>
    <div class="form-field">
    <label for="vehicle_no">Pick Up Vehicle No.:</label><input type="text" name="vehicle_no" id="vehicle_no"  />
    </div>
    
    <div class="form-field">
    <label for="report_by">Report Generated By:</label><input type="text" name="report_by" id="report_by"  value="{$user_name}"  />
    </div>
    <div class="form-field">
    <label for="report_by">Notes:</label><textarea name="notes" id="notes" rows="8" cols="17">{$notes}</textarea>
    </div>
</div>
<br clear="all" />
<input type="hidden" name="mode_action" value="import" /><br clear="all" /><br />
<div class="buttons-container buttons-bg">
<span class="submit-button cm-button-main cm-process-items">
<input type="submit" value="Continue" name="dispatch[manifest_create.manifest_generate]" class="cm-process-items" /></span>
</div>
</form>


<!--<span class="submit-button cm-button-main cm-process-items">
<input type="button" value="Cancel" onclick="javascript:history.go(-1);" class="cm-process-items" /></span> -->
