<?php
/***************************************************************************
*                                                                          *
*   (c) 2004 Vladimir V. Kalynyak, Alexey V. Vinokurov, Ilya M. Shalnev    *
*                                                                          *
* This  is  commercial  software,  only  users  who have purchased a valid *
* license  and  accept  to the terms of the  License Agreement can install *
* and use this program.                                                    *
*                                                                          *
****************************************************************************
* PLEASE READ THE FULL TEXT  OF THE SOFTWARE  LICENSE   AGREEMENT  IN  THE *
* "copyright.txt" FILE PROVIDED WITH THIS DISTRIBUTION PACKAGE.            *
****************************************************************************/


if ( !defined('AREA') ) { die('Access denied'); }

$manage_page_access = fn_check_priviledges("manage_manifest");
if($manage_page_access == '')
{
	fn_set_notification('E','Order','You cannot access this page','I');
	return array(CONTROLLER_STATUS_REDIRECT, "");
}

if ($mode == 'manifest_list') {
	
	$params = $_REQUEST;
	list($result, $search, $totals) = fn_get_manifest_all_list($params, Registry::get('settings.Appearance.admin_orders_per_page'), true);
	
	$view->assign('search', $search);
	$view->assign('totals', $totals);
	$view->assign('display_totals', 25);
	$view->assign('list_email_data', $result);
	
}

function fn_get_manifest_all_list($params, $items_per_page = 0, $get_totals = false, $lang_code = CART_LANGUAGE)
{
	// Init filter
	$params = fn_init_view('manifest_search', $params);

	// Set default values to input params
	$params['page'] = empty($params['page']) ? 1 : $params['page']; // default page is 1
	$where = '';
	
	$params['manifest_ids'] = array();
	
	/* Search by manifest ID */
	if(isset($params['manifest_id']) && $params['manifest_id'] != '')
	{
		array_push($params['manifest_ids'], $params['manifest_id']);
	}
	
	/* Search by order ID 
	if(isset($params['order_id']) && $params['order_id'] != '')
	{
		$order_manifest_id = order_manifest_details($params['order_id']);

		foreach($order_manifest_id as $k=>$v){
			array_push($params['manifest_ids'], $order_manifest_id[$k]['manifest_id']);
		}
	}*/
	
	/* Search by Company ID/Merchant Name or Order ID */
	if((isset($params['order_id']) && $params['order_id'] != '') || (isset($params['company_id']) && $params['company_id'] != ''))
	{
		$order_manifest_id = company_order_details($params['order_id'], $params['company_id']);
		foreach($order_manifest_id as $k=>$v){
			array_push($params['manifest_ids'], $order_manifest_id[$k]['manifest_id']);
		}
		if(empty($params['manifest_ids']))
		{
			array_push($params['manifest_ids'], 0);
		}
	}	
	if(!empty($params['manifest_ids']))
	{
		$manifest_ids = implode("','", $params['manifest_ids']);
		$where .= " and com.manifest_id IN ('".$manifest_ids."')";
	}
	
	/* Search by Carrier name */
	if(isset($params['carrier_name']) && $params['carrier_name'] != '')
	{
		$carrier_names = implode("','", $params['carrier_name']);
		$where .= " and com.carrier_name IN ('".$carrier_names."')";
	}
	
	/* Search by Manifest Type name */
	if(isset($params['manifest_type']) && $params['manifest_type'] != '')
	{
		$manifest_type_ids = implode("','", $params['manifest_type']);
		$where .= " and com.manifest_type_id IN ('".$manifest_type_ids."')";
	}
	
	/* Search by Dispatch date */
	if (!empty($params['period']) && $params['period'] != 'A') {

		list($params['time_from'], $params['time_to']) = fn_create_periods($params);
		//$where .= " AND man_view.comp_date between '".$params['time_from']."' AND '".$params['time_to']."'";
		$query = "SELECT date_view.manifest_id 
					FROM (SELECT manifest_id,dispatch_date,UNIX_TIMESTAMP(STR_TO_DATE(dispatch_date,'%d/%m/%Y')) as comp_date
					FROM clues_order_manifest) as date_view 
					WHERE date_view.comp_date between '".$params['time_from']."' AND '".$params['time_to']."'";
		
		$manifest_id = db_get_array($query);
		foreach($manifest_id as $k=>$v)
		{
			$manifest_id['manifest_id'][] = $manifest_id[$k]['manifest_id'];
		}
		
		if(!empty($manifest_id['manifest_id']))
		{
			$manifest_ids = implode("','", $manifest_id['manifest_id']);
		}
		
		$where .= " and com.manifest_id IN ('".$manifest_ids."')";

	}
	
	/* Search by PickUp by name */
	if(isset($params['pickup_by']) && $params['pickup_by'] != '')
	{
		$where .= " and com.pickup_by LIKE '".$params['pickup_by']."%'";
	}
	
	/* Search by Generated by name */
	if(isset($params['generated_by']) && $params['generated_by'] != '')
	{
		$where .= " and com.generated_by_name LIKE '".$params['generated_by']."%'";
	}
	
	/* Search by PickUp Location */
	if(isset($params['pickup_location']) && $params['pickup_location'] != '')
	{
		$where .= " and com.pickup_location LIKE '".$params['pickup_location']."%'";
	}
	
	// Define sort fields
	$sortings = array (
		'manifest_id' => "manifest_id",
		'carrier_name' => "carrier_name",
		'manifest_type' => "manifest_type_name",
		'notes' => "notes",
		'order_cnt' => "order_cnt",
		'pickup_location' => "pickup_location",
		'dispatch_date' => "comp_date",
	);

	$directions = array (
		'asc' => 'asc',
		'desc' => 'desc'
	);
	
	if (empty($params['sort_by']) || empty($sortings[$params['sort_by']])) {
		$params['sort_by'] = 'dispatch_date';
	}
	
	// Reverse sorting (for usage in view)
	$params['sort_order'] = $params['sort_order'] == 'desc' ? 'asc' : 'desc';


	$sorting = (is_array($sortings[$params['sort_by']]) ? implode(' ' . $directions[$params['sort_order']] . ', ', $sortings[$params['sort_by']]): $sortings[$params['sort_by']]) . ' ' . $directions[$params['sort_order']];
	
	$sorting_way = " ORDER BY ".$sorting.", manifest_id ".$directions[$params['sort_order']];

	//exit;
	$limit = '';
	if (!empty($items_per_page)) {
		
		/*$total = db_get_field("SELECT COUNT(DISTINCT man_view.manifest_id) as manifest_id FROM
								(SELECT com.manifest_id, com.carrier_name, com.dispatch_date, 
								UNIX_TIMESTAMP(STR_TO_DATE(com.dispatch_date,'%d/%m/%Y')) as comp_date, 
								com.pickup_by, com.generated_by_name, com.pickup_location, 
								com.pickup_vehicle_no, com.notes, com.manifest_type_id, 
								cmt.description as manifest_type_name 
								FROM clues_order_manifest as com 
								INNER JOIN clues_order_manifest_details as comd 
								ON com.manifest_id = comd.manifest_id 
								INNER JOIN clues_manifest_type as cmt 
								ON cmt.manifest_type_id = com.manifest_type_id) as man_view 
								WHERE 1 $where");*/
		
		$result = mysql_query("SELECT com.manifest_id, com.carrier_name, 
							  com.dispatch_date,
							  UNIX_TIMESTAMP(STR_TO_DATE(com.dispatch_date,'%d/%m/%Y')) as comp_date, 
							  com.pickup_by,com.generated_by_name, com.pickup_location, 
							  com.pickup_vehicle_no, com.notes, com.manifest_type_id,
							  cmt.description as manifest_type_name, COUNT(DISTINCT(comd.order_id)) as order_cnt
                        	  FROM clues_order_manifest as com 
                        	  INNER JOIN clues_order_manifest_details as comd ON com.manifest_id = comd.manifest_id 
                        	  INNER JOIN clues_manifest_type as cmt ON cmt.manifest_type_id = com.manifest_type_id
							WHERE 1 $where
							GROUP BY com.manifest_id");
		$total = mysql_num_rows($result);
		
		
		$limit = fn_paginate($params['page'], $total, $items_per_page);
	}

	/*$manifests = db_get_array("SELECT man_view.*, COUNT(DISTINCT comd1.order_id) as order_cnt FROM
								(SELECT com.`manifest_id`, com.`carrier_name`, 
								com.`dispatch_date`, 
								UNIX_TIMESTAMP(STR_TO_DATE(com.dispatch_date,'%d/%m/%Y')) as comp_date, 
								com.`pickup_by`, com.generated_by_name, com.pickup_location, 
								com.`pickup_vehicle_no`, com.notes, com.manifest_type_id, 
								cmt.description as manifest_type_name 
								FROM `clues_order_manifest` as com 
								INNER JOIN clues_order_manifest_details as comd 
								ON com.manifest_id = comd.manifest_id 
								INNER JOIN clues_manifest_type as cmt 
								ON cmt.manifest_type_id = com.manifest_type_id) as man_view
								INNER JOIN clues_order_manifest_details as comd1 
								ON comd1.manifest_id = man_view.manifest_id
								WHERE 1 $where 
								GROUP BY man_view.manifest_id $sorting_way $limit");*/
	
	$manifests = db_get_array("SELECT com.manifest_id, com.carrier_name, 
							  com.dispatch_date,
							  UNIX_TIMESTAMP(STR_TO_DATE(com.dispatch_date,'%d/%m/%Y')) as comp_date, 
							  com.pickup_by,com.generated_by_name, com.pickup_location, 
							  com.pickup_vehicle_no, com.notes, com.manifest_type_id,
							  cmt.description as manifest_type_name, COUNT(DISTINCT(comd.order_id)) as order_cnt
                        	  FROM clues_order_manifest as com 
                        	  INNER JOIN clues_order_manifest_details as comd ON com.manifest_id = comd.manifest_id 
                        	  INNER JOIN clues_manifest_type as cmt ON cmt.manifest_type_id = com.manifest_type_id
							WHERE 1 $where
							GROUP BY com.manifest_id $sorting_way $limit");

	fn_view_process_results('manifests', $manifests, $params, $items_per_page);

	return array($manifests, $params, ($get_totals == true ? $totals : array()));
}

?>
