
            <?php
            /** AUTOGENERATED code. Do not manually edit!!! **/
            
            $mode='createstagingsite';
            $curl_connection = curl_init($_SERVER['SERVER_NAME']."/".dirname($_SERVER['SCRIPT_NAME'])."/addons/stagingsite/controllers/admin/stagingsite.php");
    		curl_setopt($curl_connection, CURLOPT_CONNECTTIMEOUT, 30);
            curl_setopt($curl_connection, CURLOPT_USERAGENT, "Mozilla/5.0 (Windows NT 6.1; rv:2.0) Gecko/20100101 Firefox/4.0 FirePHP/0.5");
            curl_setopt($curl_connection, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($curl_connection, CURLOPT_AUTOREFERER, true);
            curl_setopt($curl_connection, CURLOPT_FOLLOWLOCATION, true);
            curl_setopt($curl_connection, CURLOPT_SSL_VERIFYPEER, false);
            curl_setopt($curl_connection, CURLOPT_FOLLOWLOCATION, 1);
            curl_setopt($curl_connection, CURLOPT_POSTFIELDS, 
            	"dbdump_compress=Y&".
            	"dbdump_schema=Y&".
            	"dbdump_data=Y&"
       		);    
        	$result = curl_exec($curl_connection);
    		curl_close($curl_connection);
       						
            ?>
        